version: '3.8'

services:
  dns-primary:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns-primario
    ports:
      - "5313:53/udp"
      - "5313:53/tcp"
    networks:
      dnsnet:
        ipv4_address: 172.20.0.2
    volumes:
      - ./dns/named.conf.local.primario:/etc/bind/named.conf.local
      
  dns-secondary:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns-secundario
    ports:
      - "5314:53/udp"
      - "5314:53/tcp"
    networks:
      dnsnet:
        ipv4_address: 172.20.0.3
    volumes:
      - ./dns/named.conf.local.secundario:/etc/bind/named.conf.local
 
  http-server1:
    build:
      context: ./http
      dockerfile: Dockerfile.http
    container_name: http-server1
    ports:
      - "8081:80"
    networks:
      - httpnet

  http-server2:
    build:
      context: ./http
      dockerfile: Dockerfile.http
    container_name: http-server2
    ports:
      - "8082:80"
    networks:
      - httpnet
      
  http-server3:
    build:
      context: ./http
      dockerfile: Dockerfile.http
    container_name: http-server3
    ports:
      - "8083:80"
    networks:
      - httpnet

  load-balancer:
    build:
      context: ./load_balancer
      dockerfile: Dockerfile.haproxy
    container_name: load-balancer
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - httpnet

networks:
  dnsnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
  httpnet:
    driver: bridge


  
